version: "3.9"

services:
  dev-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - dev_node_modules:/app/node_modules
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis://dev-redis
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - dev-redis
      - dev-pgsql
    command: yarn start:dev

  dev-redis:
    image: redis:7-alpine
    container_name: redis_service
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  dev-pgsql:
    image: bitnami/postgresql:latest
    container_name: bitnami_postgresql
    restart: always
    environment:
      - POSTGRESQL_USERNAME=${PGSQL_USERNAME}
      - POSTGRESQL_PASSWORD=${PGSQL_PASS}
      - POSTGRESQL_DATABASE=${PGSQL_DATABASE}
    ports:
      - "${PGSQL_PORT}:${PGSQL_PORT}"
    volumes:
      - postgresql_data:/bitnami/postgresql


  test-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./test:/app
      - test_node_modules:/app/node_modules
    env_file:
      - .env.test.local
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis://test-redis
      - REDIS_PORT=${REDIS_PORT}
    command: yarn test
    depends_on:
      - test-redis


  test-redis:
    image: redis:7-alpine
    container_name: redis_service_test
    env_file:
      - .env.test.local
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - test_redis_data:/data

volumes:
  dev_node_modules:
  test_node_modules:
  dev_redis_data:
  test_redis_data:
  postgresql_data:
    driver: local
