version: "3.9"

services:
  dev-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - dev_node_modules:/app/node_modules
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis://dev-redis
      - REDIS_PORT=${REDIS_PORT}
    command: nodemon --config nodemon.json server.js
    depends_on:
      - dev-redis

  dev-redis:
    image: redis:7-alpine
    container_name: redis_service
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - dev_redis_data:/data



  test-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./test:/app
      - test_node_modules:/app/node_modules
    env_file:
      - .env.test.local
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis://test-redis
      - REDIS_PORT=${REDIS_PORT}
    command: yarn test
    depends_on:
      - test-redis


  test-redis:
    image: redis:7-alpine
    container_name: redis_service_test
    env_file:
      - .env.test.local
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - test_redis_data:/data

volumes:
  dev_node_modules:
  test_node_modules:
  dev_redis_data:
  test_redis_data:
